package com.tyss.ca.enums;

public enum Course {

	JAVA_FULL_STACK, PYTHON_FULL_STACK, MEAN_STACK, MERN_STACK, DATA_SCIENCE, AI_ML, WEB_DEVELOPMENT,
	ANDROID_DEVELOPMENT, IOT, DEVOPS, CLOUD_COMPUTING;
}
